### ISSUE TITLE
Unable to find module on Python 3.6 and 3.7 but working fine on 3.8 and 3.9

### ISSUE THREAD

**Issue by radifar** [adang1345/delvewheel#17]
Hello, me and @kuelumbus are currently testing Windows wheel for  https://github.com/kuelumbus/rdkit_platform_wheels/ . After some test we found that the wheel working just fine on Python 3.8 and 3.9, but on 3.6 and 3.7 it gives the following error.

```
(rdkit-win-36) C:\Users\radif\Documents\Python>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit\__init__.py", line 20, in <module>
    _delvewheel_init_patch_0_0_14()
  File "C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit\__init__.py", line 17, in _delvewheel_init_patch_0_0_14
    WinDLL(os.path.join(libs_dir, lib))
  File "C:\Users\radif\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

More detail on kuelumbus/rdkit_platform_wheels#8

Any idea why this happened? Thanks.

**Comment by adang1345** [comment]
@radifar Do you still need help with this? Based on https://github.com/kuelumbus/rdkit_platform_wheels/issues/8#issuecomment-913196258, it looks like you figured out the cause of the problem.

**Comment by radifar** [comment]
Hi @adang1345, thank you for your response. I think we found the source of the problem yeah. And it seems not related to delvewheel, rather they probably came from the DLL packaging.

Thanks, I'll close this issue now.
