### ISSUE TITLE
Library Not Found even with add-path

### ISSUE THREAD

**Issue by WillAyd** [adang1345/delvewheel#22]
Thanks a ton for the library - this is awesome!

I am running into an issue where my wheel has some dependencies that aren't on system paths. If I do a `delvewheel show <the_wheel>` my output shows something like this:

```sh
The following DLLs will be copied into the wheel.
   ...
   arrow_python.dll (Error: Not Found)
   arrow.dll (Error: Not Found)
```

These arrow libraries are installed in C:\Program Files\arrow\lib
![image](https://user-images.githubusercontent.com/609873/149607670-48bcf33c-1b53-47d3-8ebe-691760b31a76.png)

I was hoping to resolve this by running `delvewheel show --add-path  "C:\Program Files\arrow\lib" <the_wheel> but it doesn't seem to have any effect. FWIW running with `-v` as an option doesn't increase any verbosity either

**Comment by adang1345** [comment]
I see the `.lib` files in `C:\Program Files\arrow\lib`. You'll need to enter the directory of the `.dll` files.

**Comment by WillAyd** [comment]
Ah makes total sense - chalk this up to user error. Thanks again for the great tool!
