### ISSUE TITLE
Unable to find library

### ISSUE THREAD

**Issue by pfebrer** [adang1345/delvewheel#26]
Hi! We are trying to create wheels for windows for the first time using `pypa/cibuildwheel` and `delvewheel`. Our package uses fortran extensions compiled using `f2py`. When repairing the wheel, we get this error:

```
+ delvewheel repair --no-mangle-all -w C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheelldbcha4p\repaired_wheel --add-path C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheelldbcha4p\repaired_wheel\sisl\.libs C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheelldbcha4p\built_wheel\sisl-0.1.dev1+ga06a674-cp39-cp39-win32.whl
  Traceback (most recent call last):
    File "C:\cibw\python\pythonx86.3.9.9\tools\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\cibw\python\pythonx86.3.9.9\tools\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\cibw\python\pythonx86.3.9.9\tools\Scripts\delvewheel.exe\__main__.py", line 7, in <module>
    File "C:\cibw\python\pythonx86.3.9.9\tools\lib\site-packages\delvewheel\__main__.py", line 70, in main
      wr.repair(args.target, no_mangles, args.no_mangle_all, args.lib_sdir)
    File "C:\cibw\python\pythonx86.3.9.9\tools\lib\site-packages\delvewheel\wheel_repair.py", line 392, in repair
      discovered, ignored = patch_dll.get_all_needed(extension_module_path, self._add_dlls, self._no_dlls, self._wheel_dirs)[:2]
    File "C:\cibw\python\pythonx86.3.9.9\tools\lib\site-packages\delvewheel\patch_dll.py", line 181, in get_all_needed
      raise FileNotFoundError(f'Unable to find library: {dll_name}')
  FileNotFoundError: Unable to find library: libio_m.z2qrulmp43yn7bzyxtwuv4l6mjf2c6ct.gfortran-win32.dll
  repairing C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheelldbcha4p\built_wheel\sisl-0.1.dev1+ga06a674-cp39-cp39-win32.whl
  finding DLL dependencies
```
Here are the CI logs: https://github.com/pfebrer/sisl/runs/4999376946?check_suite_focus=true
And here is the wheel that is built and we are trying to repair:
[sisl-0.1.dev1+g1b94514-cp39-cp39-win32.zip](https://github.com/adang1345/delvewheel/files/7967162/sisl-0.1.dev1%2Bg1b94514-cp39-cp39-win32.zip)

I should say that we are quite lost on how `dll` are managed by windows, so presumably we are doing things wrong :) Any pointers in the right direction would be very highly appreciated :sweat_smile: 

Thanks!

**Comment by adang1345** [comment]
The wheel you are trying to repair already has `libio_m.z2qrulmp43yn7bzyxtwuv4l6mjf2c6ct.gfortran-win32.dll` in it. By default, `delvewheel` does not check whether a DLL is already in the wheel and tries to find it from an external source. To change this behavior, use the `--ignore-in-wheel` flag.

**Comment by pfebrer** [comment]
Thank you very much! `--ignore-in-wheel` works for `windows_amd64`, but it doesn't seem to work for the 32bit version, is this intended/known?

See logs: https://github.com/pfebrer/sisl/runs/5003473146?check_suite_focus=true

**Comment by pfebrer** [comment]
Yes, it's exactly the one that I uploaded :)

**Comment by adang1345** [comment]
For the wheel you uploaded, `libio_m.z2qrulmp43yn7bzyxtwuv4l6mjf2c6ct.gfortran-win32.dll` is 64-bit. The `FileNotFoundError` is occurring because `delvewheel` is unable to find a 32-bit version of this file.

**Comment by pfebrer** [comment]
Ok, nice! I guess that solves the mistery. I have no idea how to make this file be 32-bit but it is what it is :sweat_smile: 

Thanks for the help!
