### ISSUE TITLE
Suppress delay-load?

### ISSUE THREAD

**Issue by ndw** [adang1345/delvewheel#34]
In January, I constructed some wheels with `cibuildwheel` and they came out fine. I did the same thing earlier this week and the resulting wheels have a `.pth` file that's apparently related to support for delay-load. This breaks the wheels in a virtual environment.

Is it possible to tell delvewheel not to do this?

**Comment by adang1345** [comment]
I did some further investigating and found that the support for delay-load DLLs causes some other problems as well, so I backed out the change and made a new release. Version 1.3.5 contains the fix.
