### ISSUE TITLE
DELVEWHEEL file makes reproducibility difficult

### ISSUE THREAD

**Issue by jvolkman** [adang1345/delvewheel#36]
The `DELVEWHEEL` file in `dist-info` contains the arguments passed to the program at repair time. Various build strategies will use temporary directories which then leak into this file, causing it to not be reproducible across runs.

It might be possible to setup a build environment and pass only relative paths for the input wheel, output directory, and lib paths. But with symlinking being tricky (impossible?) on Windows, that also becomes a difficult task.

It looks like only the `Version` entry in the file is used at a later time. The `Arguments` entry is stored but doesn't appear to be ever read again. Would you be open to omitting it, either outright or with some CLI option?

**Comment by adang1345** [comment]
The `Arguments` entry has been useful in diagnosing issues, so I'd like to keep it. But to support your use case, I added the `--no-diagnostic` flag.

**Comment by ofek** [comment]
Can this please be reopened so `SOURCE_DATE_EPOCH` may be supported? It appears that other patchers support this:

- https://github.com/pypa/auditwheel/pull/348
- https://github.com/matthew-brett/delocate/pull/187

**Comment by adang1345** [comment]
If you want support for `SOURCE_DATE_EPOCH`, then please open a separate issue.

**Comment by ofek** [comment]
https://github.com/adang1345/delvewheel/issues/41
