### ISSUE TITLE
unable to find msvcp140.dll when cross-compiling to ARM64 with cibuildwheel

### ISSUE THREAD

**Issue by minrk** [adang1345/delvewheel#44]
I'm [exploring building Windows ARM wheels for pyzmq](https://github.com/zeromq/pyzmq/pull/1951). This uses cibuildwheel, which cross-compiles from AMD64 to ARM64, and then invokes delvewheel. The build is succeeding, but delvewheel is not finding `msvcp140.dll`:

```
  File "C:\hostedtoolcache\windows\Python\3.11.8\x64\Lib\site-packages\delvewheel\_dll_utils.py", line 403, in get_all_needed
      raise FileNotFoundError(f'Unable to find library: {dll_name}')
  FileNotFoundError: Unable to find library: msvcp140.dll
  extracting pyzmq-26.0.0a6-cp39-cp39-win_arm64.whl to C:\Users\RUNNER~1\AppData\Local\Temp\tmpy71qzmf_
  repairing C:\Users\runneradmin\AppData\Local\Temp\cibw-run-eilqynyq\cp39-win_arm64\built_wheel\pyzmq-26.0.0a6-cp39-cp39-win_arm64.whl
  finding DLL dependencies
  analyzing package-level extension module zmq\backend\cython\_zmq.cp39-win_arm64.pyd
```

I'm guessing I just need to specify the right `--add-path` to find the arm64 DLLs, but I don't really know where these things live. Any suggestion on where to look? Should I expect the default search path to be able to find these?

This is on a GitHub Actions windows-2022 runner.

**Comment by adang1345** [comment]
The default search path that `delvewheel` uses is the `PATH` environment variable, which I would not expect to include the path to the arm64 DLLs. I think those DLLs would be somewhere under `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC`.
