### ISSUE TITLE
Docs: Provide additional resources / information about mangling

### ISSUE THREAD

**Issue by jdegenstein** [adang1345/delvewheel#46]
First off -- thanks for this great project.

We have been trying to use delvewheel on a project and noticed that when a DLL is mangled by delvewheel the e.g. SHA256 sum of the file is changed. Can the docs be expanded to include additional information about what delvewheel does to the DLLs during mangling? I think documentation here or alternatively links to external sources would be fine.

In our application, the above modification of the DLL actually made it incompatible with code running against the same (but untouched/unmangled) DLL.

**Comment by adang1345** [comment]
I'll put a more detailed description in the README, but here's a quick summary of what happens.

Suppose there is a DLL named `A.dll` which depends on `B.dll`. When `B.dll` is renamed to something like `B-3836b752f40b8c115a6e5b0e50ca4298.dll`, then `A.dll` will no longer be able to find it. Inside `A.dll`, there exists a table containing the names of the dependent DLLs, including the string `B.dll`. During the name mangling step, `delvewheel` goes into `A.dll` and modifies the table entry to instead be `B-3836b752f40b8c115a6e5b0e50ca4298.dll`. This changes the checksum of the `A.dll` file.
