### ISSUE TITLE
Missing dependency: wheel

### ISSUE THREAD

**Issue by skirpichev** [adang1345/delvewheel#48]
It seems, delvewheel assumes that this package is present.  Here is a build failure with recent cibuildwheels: https://github.com/skirpichev/gmpy/actions/runs/9156931291/job/25173450737.  Solved by last commit in https://github.com/aleaxit/gmpy/pull/483.

**Comment by adang1345** [comment]
`delvewheel` does not depend on `wheel`. In your case, the dependency on `wheel` comes from the `wheel unpack` and `wheel pack` commands at https://github.com/skirpichev/gmpy/blob/454f9579a333039cb2bc47dd994f1f5fd8fb8048/scripts/cibw_repair_wheel_command_windows.sh#L11.

**Comment by skirpichev** [comment]
Indeed.  I forgot that these parts aren't removed.  Thanks.
