### ISSUE TITLE
How to Place the DLL Folder Inside a Subdirectory of self._distribution_name

### ISSUE THREAD

**Issue by jianjian01** [adang1345/delvewheel#57]
For the parameter

```
parser_repair.add_argument('-L', '--lib-sdir', default='.libs', type=_subdir_suffix, help='directory suffix in package to store vendored DLLs (default .libs)')
```

If the library name is A, it will create a folder named A.libs. However, I want to have an A/libs directory.

In the code:
```
        if has_top_level_ext_module:
            # At least 1 extension module is top-level, so we cannot use
            # __init__.py to insert the DLL search path at runtime. In this
            # case, DLLs are instead copied into the platlib folder, whose
            # contents are installed directly into site-packages during
            # installation.
            libs_dir_name = '.'
            libs_dir = self._platlib_dir
        else:
            libs_dir_name = self._distribution_name + lib_sdir
            libs_dir = os.path.join(self._extract_dir, libs_dir_name)
        os.makedirs(libs_dir, exist_ok=True)
```

os.makedirs will directly create a directory. Shouldn't it be changed to:

```
        if has_top_level_ext_module:
            # At least 1 extension module is top-level, so we cannot use
            # __init__.py to insert the DLL search path at runtime. In this
            # case, DLLs are instead copied into the platlib folder, whose
            # contents are installed directly into site-packages during
            # installation.
            libs_dir_name = '.'
            libs_dir = self._platlib_dir
        else:
            libs_dir = os.path.join(self._extract_dir, self._distribution_name, lib_sdir)
        os.makedirs(libs_dir, exist_ok=True)
```

**Comment by adang1345** [comment]
The current design is borrowed from the `auditwheel` project, and https://github.com/pypa/auditwheel/issues/89 contains the discussion that led `auditwheel` to this design. The reasons behind the linked discussion apply to `delvewheel` as well, and here is a summary list of reasons behind the current design.

- The distribution name of the wheel does not have to match the package name inside the wheel. So a wheel named `A`, might not contain an `A` package.
- The wheel can have multiple top-level packages. So a wheel named `A` might contain packages named `B` and `C`, which are importable via `import B` or `import C`. Having these packages share a single `A.libs` directory for DLL dependencies reduces duplication compared to having both `B/libs` and `C/libs`.
- If the `A/libs` directory exists, then it causes an unwanted side effect of being importable via `import A.libs`.
- The wheel might have a top-level namespace package named `A`, where having `A/libs` could cause conflicts with other wheels that also have a top-level namespace package `A`.

Putting the DLLs in a folder like `A.libs` avoids all these issues.

**Comment by jianjian01** [comment]
Got it, I understand your point. Thank you for your response.

However, I have a bit of OCD, and I prefer to have my dependencies placed in the A/.lib subdirectory. Is it possible to provide an option for that?

**Comment by adang1345** [comment]
Sorry, the benefit of adding this option is not enough to justify the complexity involved in implementing and maintaining the option. The current implementation is simpler and works across many Python project structures.
